packages:
  - "examples/*"
  - "packages/*"
  - "!**/node_modules"
  - "!**/dist"
  - "!**/build"
  - "!**/test"
allowBuilds:
  esbuild: false

catalog:
  "@types/node": "^25.5.0"
  "@typescript/native-preview": "^7.0.0-dev.20260319.1"
  "axios": "^1.13.6"
  "bumpp": "^10.4.1"
  "console-table-printer": "^2.15.0"
  "es-toolkit": "^1.45.1"
  "openapi3-ts": "^4.5.0"
  "oxfmt": "^0.41.0"
  "picocolors": "^1.1.1"
  "rimraf": "^6.1.3"
  "tsdown": "^0.21.0"
  "turbo": "^2.8.17"
  "typescript": "^6.0.0-beta"
  "unconfig": "^7.5.0"
  "jsdom": "^29.0.0"
  "@vitest/coverage-v8": "^4.1.0"
  "vitest": "^4.1.0"
  # demo
  "vite": "^8.0.0"
  "un-api-builder": "latest"
