// 当前文件由 un-api-builder 自动生成-非必要请勿手动修改此文件
import * as apis from './apis/index.ts';
import { createMemoryDoc } from 'un-api-builder/browser';
/**
 * | 所属模块 | 接口名 | URL地址 | 请求类型 | 接口描述 |
 * | --- | --- | --- | --- | --- |
 * | file | postUpload | /file/upload | POST | 上传文件（FormData） |
 * | file | postUploadList | /file/upload/list | POST | 批量上传文件（FormData） |
 * | file | postUploadListBase64 | /file/upload/list/base64 | POST | 批量上传文件（Base64） |
 * | file | getDownload | /file/download | GET | 下载文件 |
 * | user | putById | /user/{id} | PUT | 修改用户信息 |
 * | user | post | /user | POST | 新增用户信息 |
 * | user | postList | /user/list | POST | 根据userId集合获取用户列表 |
 * | user | postListByAccount | /user/listByAccount | POST | 根据accountId集合获取用户列表 |
 * | user | getPage | /user/page | GET | 分页查询 |
 * | user | getGetIMLink | /user/getIMLink | GET | 获取IM连接加密信息 |
 * | user | getGetAccountInfo | /user/getAccountInfo | GET | 获取当前登录用户的信息 |
 * | systemMessage | putReadById | /systemMessage/read/{id} | PUT | 指定消息为已读状态 |
 * | systemMessage | getPage | /systemMessage/page | GET | 分页查询 |
 * | systemMessage | getCurrentPage | /systemMessage/current/page | GET | 分页查询当前登录用户的系统消息 |
 * | role | getById | /role/{id} | GET | 根据ID查询一条数据 |
 * | role | putById | /role/{id} | PUT | 根据id修改一条数据 |
 * | role | deleteById | /role/{id} | DELETE | 根据id删除数据 |
 * | role | putList | /role/list | PUT | 批量修改数据 |
 * | role | postList | /role/list | POST | 批量添加数据 |
 * | role | deleteList | /role/list | DELETE | 根据id集合批量删除数据 |
 * | role | post | /role | POST | 添加一条数据 |
 * | role | postListQuery | /role/list/query | POST | 根据id集合获取列表 |
 * | role | getPage | /role/page | GET | 分页查询 |
 * | project | put | /project | PUT | 修改项目 |
 * | project | post | /project | POST | 新增项目 |
 * | project | postList | /project/list | POST | 根据id集合获取列表 |
 * | project | getPage | /project/page | GET | 分页查询 |
 * | project | putStatusChange | /project/statusChange | PUT | 修改项目状态 |
 * | project | postStatusChange | /project/statusChange | POST | 新增项目状态 |
 * | project | postStatusChangeList | /project/statusChange/list | POST | 根据id集合获取列表 |
 * | project | getStatusChangePage | /project/statusChange/page | GET | 分页查询 |
 * | project | putLifeCycle | /project/lifeCycle | PUT | 修改任务 |
 * | project | postLifeCycle | /project/lifeCycle | POST | 新增任务 |
 * | project | putLifeCycleStatus | /project/lifeCycle/status | PUT | 修改状态 |
 * | project | postLifeCycleList | /project/lifeCycle/list | POST | 根据id集合获取列表 |
 * | project | getLifeCyclePage | /project/lifeCycle/page | GET | 分页查询 |
 * | projectCategory | putById | /projectCategory/{id} | PUT | 修改类目数据 |
 * | projectCategory | putStatus | /projectCategory/status | PUT | 批量修改状态 |
 * | projectCategory | post | /projectCategory | POST | 新增类目数据 |
 * | projectCategory | postList | /projectCategory/list | POST | 根据id集合获取列表 |
 * | projectCategory | getPage | /projectCategory/page | GET | 分页查询 |
 * | permissionMenus | getById | /permissionMenus/{id} | GET | 根据ID查询一条数据 |
 * | permissionMenus | putById | /permissionMenus/{id} | PUT | 根据id修改一条数据 |
 * | permissionMenus | deleteById | /permissionMenus/{id} | DELETE | 根据id删除数据 |
 * | permissionMenus | putList | /permissionMenus/list | PUT | 批量修改数据 |
 * | permissionMenus | postList | /permissionMenus/list | POST | 批量添加数据 |
 * | permissionMenus | deleteList | /permissionMenus/list | DELETE | 根据id集合批量删除数据 |
 * | permissionMenus | post | /permissionMenus | POST | 添加一条数据 |
 * | permissionMenus | postListQuery | /permissionMenus/list/query | POST | 根据id集合获取列表 |
 * | permissionMenus | getPage | /permissionMenus/page | GET | 分页查询 |
 * | permissionMenus | getCurrent | /permissionMenus/current | GET | 获取当前登录用户拥有的菜单功能权限 |
 * | financeCategory | putById | /financeCategory/{id} | PUT | 修改类目数据 |
 * | financeCategory | putStatus | /financeCategory/status | PUT | 批量修改状态 |
 * | financeCategory | post | /financeCategory | POST | 新增类目数据 |
 * | financeCategory | postList | /financeCategory/list | POST | 根据id集合获取列表 |
 * | financeCategory | getPage | /financeCategory/page | GET | 分页查询 |
 * | finance | putById | /finance/{id} | PUT | 修改资金批次 |
 * | finance | putStatus | /finance/status | PUT | 批量修改状态 |
 * | finance | post | /finance | POST | 新增资金批次 |
 * | finance | postList | /finance/list | POST | 根据id集合获取列表 |
 * | finance | getPage | /finance/page | GET | 分页查询 |
 * | finance | putDepartmentById | /finance/department/{id} | PUT | 修改分配给部门的资金 |
 * | finance | putDepartmentStatus | /finance/department/status | PUT | 批量修改状态 |
 * | finance | postDepartment | /finance/department | POST | 新增资金分配给部门（从批次上分配给顶级部门） |
 * | finance | postDepartmentList | /finance/department/list | POST | 根据id集合获取列表 |
 * | finance | postDepartmentChild | /finance/department/child | POST | 新增资金分配给部门（分配给子部门） |
 * | finance | getDepartmentPage | /finance/department/page | GET | 分页查询 |
 * | finance | putCategoryById | /finance/category/{id} | PUT | 修改部门分配资金类目 |
 * | finance | putCategoryStatus | /finance/category/status | PUT | 批量修改状态 |
 * | finance | postCategory | /finance/category | POST | 新增部门下资金分配给类目 |
 * | finance | postCategoryList | /finance/category/list | POST | 根据id集合获取列表 |
 * | finance | getCategoryPage | /finance/category/page | GET | 分页查询 |
 * | finance | postCategoryProjectByAllocationCategoryId | /finance/category/project/{allocationCategoryId} | POST | 批量关联项目类目id |
 * | finance | getCategoryProjectPage | /finance/category/project/page | GET | 分页查询 |
 * | dictType | putById | /dictType/{id} | PUT | 修改字典类型 |
 * | dictType | deleteById | /dictType/{id} | DELETE | 删除字典类型 |
 * | dictType | putStatusById | /dictType/status/{id} | PUT | 修改状态 |
 * | dictType | post | /dictType | POST | 新增字典类型 |
 * | dictType | getPage | /dictType/page | GET | 分页查询 |
 * | dictType | deleteList | /dictType/list | DELETE | 批量删除字典类型 |
 * | dictData | putById | /dictData/{id} | PUT | 修改字典数据 |
 * | dictData | deleteById | /dictData/{id} | DELETE | 删除字典数据 |
 * | dictData | putStatusById | /dictData/status/{id} | PUT | 修改状态 |
 * | dictData | post | /dictData | POST | 新增字典数据 |
 * | dictData | getPage | /dictData/page | GET | 分页查询 |
 * | dictData | deleteList | /dictData/list | DELETE | 批量删除字典数据 |
 * | department | putById | /department/{id} | PUT | 修改部门数据 |
 * | department | deleteById | /department/{id} | DELETE | 删除部门数据 |
 * | department | putStatus | /department/status | PUT | 批量修改状态 |
 * | department | post | /department | POST | 新增部门数据 |
 * | department | postList | /department/list | POST | 根据id集合获取列表 |
 * | department | deleteList | /department/list | DELETE | 批量删除部门数据 |
 * | department | getPage | /department/page | GET | 分页查询 |
 * | config | putUpdate | /config/update | PUT | 修改系统配置(自定义) |
 * | config | postSave | /config/save | POST | 新增系统配置(自定义) |
 * | config | getItem | /config/item | GET | 根据key获取配置项 |
 * | config | getEnums | /config/enums | GET | 获取所有枚举信息 |
 * | approval | put | /approval | PUT | 修改 |
 * | approval | post | /approval | POST | 新增 |
 * | approval | postList | /approval/list | POST | 根据id集合获取列表 |
 * | approval | deleteList | /approval/list | DELETE | 批量删除 |
 * | approval | postHistoryPage | /approval/history/page | POST | 分配历史记录分页查询 |
 * | approval | getPage | /approval/page | GET | 分页查询 |
 * | approval | getHistoryByApprovalIdByLot | /approval/history/{approvalId}/{lot} | GET | 获取指定单子指定阶段最新的审批人知会人 |
 * | approval | deleteById | /approval/{id} | DELETE | 删除 |
 * | approval | putRecord | /approval/record | PUT | 修改 |
 * | approval | postRecord | /approval/record | POST | 新增 |
 * | approval | putRecordBack | /approval/record/back | PUT | 退回 |
 * | approval | postRecordList | /approval/record/list | POST | 根据id集合获取列表 |
 * | approval | getRecordPage | /approval/record/page | GET | 分页查询 |
 * | approval | deleteRecordById | /approval/record/{id} | DELETE | 删除 |
 * | account | putUpdatePasswordCurrent | /account/updatePassword/current | PUT | 当前登录用户修改密码 |
 * | account | putUpdatePasswordAdmin | /account/updatePassword/admin | PUT | 超管修改指定用户密码 |
 * | account | putStatus | /account/status | PUT | 批量修改状态 |
 * | account | postLogin | /account/login | POST | 用户登录 |
 * | logInfo | getPage | /logInfo/page | GET | 分页查询 |
 */
export const apiYusuan = createMemoryDoc(apis,({url,...ops})=>globalThis.fetch(url, ops));